#!/bin/bash

# UOM Database Migration Manual Application Guide
# Since Supabase CLI isn't working, follow these steps:

echo "🔧 UOM Database Migration Manual Application"
echo "==========================================="
echo ""
echo "Since Supabase CLI isn't working, please apply the UOM migration manually:"
echo ""
echo "1. Open your Supabase project dashboard"
echo "2. Go to SQL Editor"
echo "3. Copy and paste the content from one of these files:"
echo "   - UOM_MIGRATION_STANDALONE.sql (recommended)"
echo "   - supabase/migrations/20251008000002_integrate_uom_with_existing_schema.sql"
echo ""
echo "4. Click 'Run' to execute the migration"
echo ""
echo "The migration will:"
echo "   ✅ Add UOM columns to existing tables (products, region_pricing, order_items)"
echo "   ✅ Create new UOM tables (uom_units, uom_conversions, uom_pricing)"
echo "   ✅ Insert default UOM units (pcs, box, carton, kg, etc.)"
echo "   ✅ Set up proper indexes and constraints"
echo ""
echo "5. After running the migration, test a product in SKU Management:"
echo "   - Open Admin → SKU Management"
echo "   - Edit a product (e.g., 'Test SKU')"
echo "   - Set MOQ UOM to 'carton' instead of 'pcs'"
echo "   - Save the product"
echo "   - Check the product list to see if MOQ shows 'carton'"
echo ""
echo "6. Check browser console for UOM debug logs to verify data is being fetched"
echo ""
echo "If you need help applying the migration, the UOM_MIGRATION_STANDALONE.sql file"
echo "contains the complete migration with all necessary changes."