/**
 * Product and Variant Injection Script
 * 
 * This script injects products, variants, and region pricing data from a CSV file
 * into the Supabase database. It handles non-unique SKU IDs and properly structures
 * the data with proper relationships between products, variants and regions.
 */

import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { parse } from 'csv-parse/sync';
import dotenv from 'dotenv';

dotenv.config();

// Initialize Supabase client
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_ANON_KEY || '';
const supabase = createClient(supabaseUrl, supabaseKey);

// Define the CSV file path
const csvFilePath = path.resolve(process.cwd(), 'data', 'products-list.csv');

// Define interfaces to match our DB schema
interface ProductCSVRow {
  'SKU ID': string;
  'Category': string;
  'Brand': string;
  'Product Name': string;
  'Size': string;
  'Unnamed: 5': string;  // Combined product name + size
  'Variants': string;
  'Distribution Area': string;
  'Distributor Price (Ctn)': string;
  'Distributor Price (Pcs)': string;
  'Consumer Price (Ctn)': string;
  'Consumer Price (Pcs)': string;
  'Pcs per Ctn': string;
  'MOQ': string;
  'Product Picture': string;
}

interface ProductRecord {
  id?: string;  // UUID will be generated by Supabase
  sku: string;
  name: string;
  size: string;
  description: string;
  base_distributor_price: number;
  consumer_price: number;
  base_moq: number;
  image_url: string;
  brand_id: string;
  category_id: string;
  has_variants: boolean;
  stock_quantity: number;
}

interface VariantRecord {
  product_id: string;  // FK to products table
  variant_name: string;
  additional_price: number;
  is_active: boolean;
  sku: string;  // Each variant gets its own SKU
}

interface RegionPricingRecord {
  product_id: string;  // FK to products table
  area: string;
  distributor_price: number;
  moq: number;
}

interface BrandRecord {
  id?: string;  // UUID will be generated by Supabase
  name: string;
}

interface CategoryRecord {
  id?: string;  // UUID will be generated by Supabase
  name: string;
}

async function main() {
  try {
    // 1. Read and parse CSV file
    console.log('Reading CSV file...');
    const fileContent = fs.readFileSync(csvFilePath, 'utf-8');
    const records: ProductCSVRow[] = parse(fileContent, {
      columns: true,
      skip_empty_lines: true,
    });
    console.log(`Found ${records.length} rows in CSV`);

    // 2. Extract unique brands and categories
    const uniqueBrands = new Set<string>();
    const uniqueCategories = new Set<string>();
    
    records.forEach(record => {
      uniqueBrands.add(record.Brand);
      uniqueCategories.add(record.Category);
    });
    
    console.log(`Found ${uniqueBrands.size} unique brands and ${uniqueCategories.size} unique categories`);
    
    // 3. Insert brands into database and get mappings
    console.log('Inserting brands...');
    const brandMap = new Map<string, string>(); // Map brand name to ID
    
    for (const brandName of uniqueBrands) {
      // Check if brand already exists
      const { data: existingBrands, error: brandQueryError } = await supabase
        .from('brands')
        .select('id')
        .eq('name', brandName);
        
      if (brandQueryError) {
        console.error(`Error checking brand ${brandName}:`, brandQueryError);
        continue;
      }
      
      let brandId: string;
      
      if (existingBrands && existingBrands.length > 0) {
        brandId = existingBrands[0].id;
        console.log(`Brand "${brandName}" already exists with ID ${brandId}`);
      } else {
        // Insert new brand
        const { data: newBrand, error: brandInsertError } = await supabase
          .from('brands')
          .insert({ name: brandName })
          .select('id')
          .single();
          
        if (brandInsertError) {
          console.error(`Error inserting brand ${brandName}:`, brandInsertError);
          continue;
        }
        
        brandId = newBrand.id;
        console.log(`Created brand "${brandName}" with ID ${brandId}`);
      }
      
      brandMap.set(brandName, brandId);
    }

    // 4. Insert categories into database and get mappings
    console.log('Inserting categories...');
    const categoryMap = new Map<string, string>(); // Map category name to ID
    
    for (const categoryName of uniqueCategories) {
      // Check if category already exists
      const { data: existingCategories, error: categoryQueryError } = await supabase
        .from('product_categories')
        .select('id')
        .eq('name', categoryName);
        
      if (categoryQueryError) {
        console.error(`Error checking category ${categoryName}:`, categoryQueryError);
        continue;
      }
      
      let categoryId: string;
      
      if (existingCategories && existingCategories.length > 0) {
        categoryId = existingCategories[0].id;
        console.log(`Category "${categoryName}" already exists with ID ${categoryId}`);
      } else {
        // Insert new category
        const { data: newCategory, error: categoryInsertError } = await supabase
          .from('product_categories')
          .insert({ name: categoryName })
          .select('id')
          .single();
          
        if (categoryInsertError) {
          console.error(`Error inserting category ${categoryName}:`, categoryInsertError);
          continue;
        }
        
        categoryId = newCategory.id;
        console.log(`Created category "${categoryName}" with ID ${categoryId}`);
      }
      
      categoryMap.set(categoryName, categoryId);
    }

    // 5. Group rows by product (base SKU) to identify unique products
    const productGroups = new Map<string, ProductCSVRow[]>();
    
    records.forEach(record => {
      const key = `${record['SKU ID']}_${record['Product Name']}_${record.Size}`;
      if (!productGroups.has(key)) {
        productGroups.set(key, []);
      }
      productGroups.get(key)?.push(record);
    });
    
    console.log(`Grouped into ${productGroups.size} unique products`);

    // 6. Insert products and their variants
    for (const [productKey, productRows] of productGroups) {
      // Use the first row as the base product information
      const baseRow = productRows[0];
      
      // Parse numeric values, removing commas and handling formatting
      const cleanNumber = (str: string) => parseFloat(str.replace(/,/g, ''));
      
      // Process the image URL to make it usable
      const imageUrl = baseRow['Product Picture'].replace('view?usp=drive_link', 'preview');
      
      // Determine if product has variants
      const hasVariants = baseRow.Variants.trim() !== '';
      
      // Get brand and category IDs
      const brandId = brandMap.get(baseRow.Brand);
      const categoryId = categoryMap.get(baseRow.Category);
      
      if (!brandId || !categoryId) {
        console.error(`Missing brand or category ID for product ${productKey}`);
        continue;
      }

      // Create product record
      const productData: ProductRecord = {
        sku: baseRow['SKU ID'],
        name: baseRow['Product Name'],
        size: baseRow.Size,
        description: `${baseRow.Brand} ${baseRow['Product Name']} - ${baseRow.Size}`,
        base_distributor_price: cleanNumber(baseRow['Distributor Price (Ctn)']),
        consumer_price: cleanNumber(baseRow['Consumer Price (Ctn)']),
        base_moq: cleanNumber(baseRow.MOQ),
        image_url: imageUrl,
        brand_id: brandId,
        category_id: categoryId,
        has_variants: hasVariants,
        stock_quantity: 1000,  // Default stock quantity
      };
      
      // Insert product
      console.log(`Inserting product: ${productData.name} (${productData.sku})`);
      const { data: product, error: productError } = await supabase
        .from('products')
        .insert(productData)
        .select('id')
        .single();
        
      if (productError) {
        console.error(`Error inserting product ${productData.sku}:`, productError);
        continue;
      }
      
      const productId = product.id;
      console.log(`Created product with ID ${productId}`);

      // 7. Insert variants if applicable
      const uniqueVariants = new Set(productRows.map(row => row.Variants).filter(v => v.trim() !== ''));
      
      if (uniqueVariants.size > 0) {
        console.log(`Inserting ${uniqueVariants.size} variants for product ${productData.sku}`);
        
        for (const variantName of uniqueVariants) {
          const variantSku = `${productData.sku}-${variantName.replace(/\s+/g, '-').toLowerCase()}`;
          
          const variantData: VariantRecord = {
            product_id: productId,
            variant_name: variantName,
            additional_price: 0, // No additional price in this data set
            is_active: true,
            sku: variantSku,
          };
          
          const { error: variantError } = await supabase
            .from('product_variants')
            .insert(variantData);
            
          if (variantError) {
            console.error(`Error inserting variant ${variantName} for product ${productData.sku}:`, variantError);
          } else {
            console.log(`Created variant "${variantName}" for product ${productData.sku}`);
          }
        }
      }

      // 8. Insert region pricing
      const uniqueRegions = new Map<string, { price: number, moq: number }>();
      
      productRows.forEach(row => {
        const area = row['Distribution Area'];
        const price = cleanNumber(row['Distributor Price (Ctn)']);
        const moq = cleanNumber(row.MOQ);
        
        // Use the last value if there are duplicates
        uniqueRegions.set(area, { price, moq });
      });
      
      console.log(`Inserting ${uniqueRegions.size} region pricing records for product ${productData.sku}`);
      
      for (const [area, { price, moq }] of uniqueRegions) {
        const regionData: RegionPricingRecord = {
          product_id: productId,
          area,
          distributor_price: price,
          moq,
        };
        
        const { error: regionError } = await supabase
          .from('region_pricing')
          .insert(regionData);
          
        if (regionError) {
          console.error(`Error inserting region pricing for ${area}:`, regionError);
        } else {
          console.log(`Created region pricing for area "${area}" with price ${price} and MOQ ${moq}`);
        }
      }
    }
    
    console.log('Product import completed successfully!');
    
  } catch (error) {
    console.error('Error in data import:', error);
  }
}

main().catch(console.error);
