// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vndmzsevzzjblcpovehe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZG16c2V2enpqYmxjcG92ZWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTExMDIsImV4cCI6MjA3MTg2NzEwMn0.0cY-PViJHpDu-XfSKR_6LW9LYfJLnztViK6UA41cOFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});