// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sahllcduqzfvhiohgpro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhaGxsY2R1cXpmdmhpb2hncHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTQzNDksImV4cCI6MjA3MTkzMDM0OX0.4aMlUGFmjdOJDOaEzLeHH_oA-cdghqmJAWhmUxZYQgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});